/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) g_InverseKinematics_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[64] = {6, 18, 0, 2, 5, 8, 10, 13, 16, 20, 26, 32, 34, 37, 40, 40, 40, 40, 41, 42, 43, 4, 5, 3, 4, 5, 3, 4, 5, 4, 5, 3, 4, 5, 3, 4, 5, 1, 2, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5};
static const casadi_int casadi_s3[61] = {6, 18, 0, 2, 5, 8, 10, 13, 16, 20, 26, 32, 34, 37, 40, 40, 40, 40, 40, 40, 40, 4, 5, 3, 4, 5, 3, 4, 5, 4, 5, 3, 4, 5, 3, 4, 5, 1, 2, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 4, 5, 3, 4, 5, 3, 4, 5};

/* g_InverseKinematics_Task:(q[18])->(Task[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a6, a7, a8, a9;
  a0=-1.9600000000000001e-01;
  a1=-2.1149999999999999e-01;
  a2=arg[0]? arg[0][7] : 0;
  a3=sin(a2);
  a4=(a1*a3);
  a4=(a0+a4);
  a5=-2.3039000000000001e-01;
  a6=cos(a2);
  a7=arg[0]? arg[0][8] : 0;
  a8=sin(a7);
  a9=(a6*a8);
  a10=cos(a7);
  a11=(a3*a10);
  a9=(a9+a11);
  a11=(a5*a9);
  a11=(a4+a11);
  a12=5.0000000000000000e-01;
  a13=cos(a7);
  a6=(a6*a13);
  a7=sin(a7);
  a14=(a3*a7);
  a6=(a6-a14);
  a6=(a12*a6);
  a9=(a12*a9);
  a6=(a6+a9);
  a6=(a11+a6);
  if (res[0]!=0) res[0][0]=a6;
  a6=4.9664000000000000e-02;
  a9=7.7476000000000003e-02;
  a14=arg[0]? arg[0][6] : 0;
  a15=cos(a14);
  a16=(a9*a15);
  a16=(a6+a16);
  a17=sin(a14);
  a18=cos(a2);
  a19=(a17*a18);
  a20=(a1*a19);
  a20=(a16-a20);
  a2=sin(a2);
  a17=(a17*a2);
  a21=(a17*a8);
  a22=(a19*a10);
  a21=(a21-a22);
  a22=(a5*a21);
  a22=(a20+a22);
  a17=(a17*a13);
  a23=(a19*a7);
  a17=(a17+a23);
  a17=(a12*a17);
  a23=(a12*a15);
  a17=(a17+a23);
  a21=(a12*a21);
  a17=(a17+a21);
  a17=(a22+a17);
  if (res[0]!=0) res[0][1]=a17;
  a17=sin(a14);
  a21=(a9*a17);
  a14=cos(a14);
  a18=(a14*a18);
  a23=(a1*a18);
  a23=(a21+a23);
  a10=(a18*a10);
  a14=(a14*a2);
  a8=(a14*a8);
  a10=(a10-a8);
  a8=(a5*a10);
  a8=(a23+a8);
  a2=(a12*a17);
  a14=(a14*a13);
  a7=(a18*a7);
  a14=(a14+a7);
  a14=(a12*a14);
  a2=(a2-a14);
  a12=(a12*a10);
  a2=(a2+a12);
  a2=(a8+a2);
  if (res[0]!=0) res[0][2]=a2;
  a2=3.2999999999999998e+00;
  a12=arg[0]? arg[0][15] : 0;
  a12=(a2*a12);
  a10=2.0000000000000004e-02;
  a14=1.4999999999999999e-01;
  a7=arg[0]? arg[0][10] : 0;
  a13=sin(a7);
  a24=(a1*a13);
  a24=(a0+a24);
  a25=cos(a7);
  a26=arg[0]? arg[0][11] : 0;
  a27=sin(a26);
  a25=(a25*a27);
  a26=cos(a26);
  a28=(a13*a26);
  a25=(a25+a28);
  a25=(a5*a25);
  a25=(a24+a25);
  a25=(a14*a25);
  a28=6.4000000000000001e-02;
  a24=(a28*a24);
  a29=6.3400000000000001e-01;
  a30=-1.1000000000000000e-01;
  a13=(a30*a13);
  a13=(a0+a13);
  a13=(a29*a13);
  a31=-1.1172000000000000e-01;
  a11=(a14*a11);
  a4=(a28*a4);
  a3=(a30*a3);
  a0=(a0+a3);
  a0=(a29*a0);
  a3=1.9600000000000001e-01;
  a32=arg[0]? arg[0][4] : 0;
  a33=sin(a32);
  a34=(a1*a33);
  a34=(a3+a34);
  a35=cos(a32);
  a36=arg[0]? arg[0][5] : 0;
  a37=sin(a36);
  a35=(a35*a37);
  a36=cos(a36);
  a38=(a33*a36);
  a35=(a35+a38);
  a35=(a5*a35);
  a35=(a34+a35);
  a35=(a14*a35);
  a34=(a28*a34);
  a33=(a30*a33);
  a33=(a3+a33);
  a33=(a29*a33);
  a38=1.1172000000000000e-01;
  a39=arg[0]? arg[0][1] : 0;
  a40=sin(a39);
  a41=(a1*a40);
  a41=(a3+a41);
  a42=cos(a39);
  a43=arg[0]? arg[0][2] : 0;
  a44=sin(a43);
  a42=(a42*a44);
  a43=cos(a43);
  a45=(a40*a43);
  a42=(a42+a45);
  a42=(a5*a42);
  a42=(a41+a42);
  a42=(a14*a42);
  a41=(a28*a41);
  a40=(a30*a40);
  a3=(a3+a40);
  a3=(a29*a3);
  a3=(a3+a38);
  a41=(a41+a3);
  a42=(a42+a41);
  a38=(a38+a42);
  a33=(a33+a38);
  a34=(a34+a33);
  a35=(a35+a34);
  a35=(a31+a35);
  a0=(a0+a35);
  a4=(a4+a0);
  a11=(a11+a4);
  a31=(a31+a11);
  a13=(a13+a31);
  a24=(a24+a13);
  a25=(a25+a24);
  a10=(a10+a25);
  a12=(a12+a10);
  a10=9.4430000000000014e+00;
  a12=(a12/a10);
  if (res[0]!=0) res[0][3]=a12;
  a12=arg[0]? arg[0][16] : 0;
  a12=(a2*a12);
  a25=-4.9664000000000000e-02;
  a24=-7.7476000000000003e-02;
  a13=arg[0]? arg[0][9] : 0;
  a31=cos(a13);
  a11=(a24*a31);
  a11=(a25+a11);
  a4=sin(a13);
  a0=cos(a7);
  a35=(a4*a0);
  a34=(a1*a35);
  a34=(a11-a34);
  a7=sin(a7);
  a4=(a4*a7);
  a4=(a4*a27);
  a33=(a35*a26);
  a4=(a4-a33);
  a4=(a5*a4);
  a4=(a34+a4);
  a4=(a14*a4);
  a34=(a28*a34);
  a33=1.6000000000000000e-02;
  a38=(a33*a31);
  a35=(a30*a35);
  a38=(a38-a35);
  a11=(a11+a38);
  a11=(a29*a11);
  a38=5.6999999999999995e-01;
  a35=3.5999999999999997e-02;
  a31=(a35*a31);
  a31=(a25+a31);
  a31=(a38*a31);
  a22=(a14*a22);
  a20=(a28*a20);
  a42=-1.6000000000000000e-02;
  a41=(a42*a15);
  a19=(a30*a19);
  a41=(a41-a19);
  a16=(a16+a41);
  a16=(a29*a16);
  a41=-3.5999999999999997e-02;
  a15=(a41*a15);
  a15=(a6+a15);
  a15=(a38*a15);
  a19=arg[0]? arg[0][3] : 0;
  a3=cos(a19);
  a40=(a24*a3);
  a40=(a25+a40);
  a45=sin(a19);
  a46=cos(a32);
  a47=(a45*a46);
  a48=(a1*a47);
  a48=(a40-a48);
  a32=sin(a32);
  a45=(a45*a32);
  a45=(a45*a37);
  a49=(a47*a36);
  a45=(a45-a49);
  a45=(a5*a45);
  a45=(a48+a45);
  a45=(a14*a45);
  a48=(a28*a48);
  a49=(a33*a3);
  a47=(a30*a47);
  a49=(a49-a47);
  a40=(a40+a49);
  a40=(a29*a40);
  a3=(a35*a3);
  a25=(a25+a3);
  a25=(a38*a25);
  a3=arg[0]? arg[0][0] : 0;
  a49=cos(a3);
  a47=(a9*a49);
  a47=(a6+a47);
  a50=sin(a3);
  a51=cos(a39);
  a52=(a50*a51);
  a53=(a1*a52);
  a53=(a47-a53);
  a39=sin(a39);
  a50=(a50*a39);
  a50=(a50*a44);
  a54=(a52*a43);
  a50=(a50-a54);
  a50=(a5*a50);
  a50=(a53+a50);
  a50=(a14*a50);
  a53=(a28*a53);
  a54=(a42*a49);
  a52=(a30*a52);
  a54=(a54-a52);
  a47=(a47+a54);
  a47=(a29*a47);
  a49=(a41*a49);
  a6=(a6+a49);
  a6=(a38*a6);
  a47=(a47+a6);
  a53=(a53+a47);
  a50=(a50+a53);
  a25=(a25+a50);
  a40=(a40+a25);
  a48=(a48+a40);
  a45=(a45+a48);
  a15=(a15+a45);
  a16=(a16+a15);
  a20=(a20+a16);
  a22=(a22+a20);
  a31=(a31+a22);
  a11=(a11+a31);
  a34=(a34+a11);
  a4=(a4+a34);
  a12=(a12+a4);
  a12=(a12/a10);
  if (res[0]!=0) res[0][4]=a12;
  a12=arg[0]? arg[0][17] : 0;
  a2=(a2*a12);
  a12=2.5110000000000000e-02;
  a4=-1.2000000000000000e-02;
  a34=sin(a13);
  a11=(a24*a34);
  a13=cos(a13);
  a0=(a13*a0);
  a31=(a1*a0);
  a31=(a11+a31);
  a26=(a0*a26);
  a13=(a13*a7);
  a13=(a13*a27);
  a26=(a26-a13);
  a26=(a5*a26);
  a26=(a31+a26);
  a26=(a14*a26);
  a31=(a28*a31);
  a13=(a33*a34);
  a0=(a30*a0);
  a13=(a13+a0);
  a11=(a11+a13);
  a11=(a29*a11);
  a34=(a35*a34);
  a34=(a38*a34);
  a8=(a14*a8);
  a23=(a28*a23);
  a13=(a42*a17);
  a18=(a30*a18);
  a13=(a13+a18);
  a21=(a21+a13);
  a21=(a29*a21);
  a17=(a41*a17);
  a17=(a38*a17);
  a13=sin(a19);
  a24=(a24*a13);
  a19=cos(a19);
  a46=(a19*a46);
  a18=(a1*a46);
  a18=(a24+a18);
  a36=(a46*a36);
  a19=(a19*a32);
  a19=(a19*a37);
  a36=(a36-a19);
  a36=(a5*a36);
  a36=(a18+a36);
  a36=(a14*a36);
  a18=(a28*a18);
  a33=(a33*a13);
  a46=(a30*a46);
  a33=(a33+a46);
  a24=(a24+a33);
  a24=(a29*a24);
  a35=(a35*a13);
  a35=(a38*a35);
  a13=sin(a3);
  a9=(a9*a13);
  a3=cos(a3);
  a51=(a3*a51);
  a1=(a1*a51);
  a1=(a9+a1);
  a43=(a51*a43);
  a3=(a3*a39);
  a3=(a3*a44);
  a43=(a43-a3);
  a5=(a5*a43);
  a5=(a1+a5);
  a14=(a14*a5);
  a28=(a28*a1);
  a42=(a42*a13);
  a30=(a30*a51);
  a42=(a42+a30);
  a9=(a9+a42);
  a29=(a29*a9);
  a41=(a41*a13);
  a38=(a38*a41);
  a29=(a29+a38);
  a28=(a28+a29);
  a14=(a14+a28);
  a35=(a35+a14);
  a24=(a24+a35);
  a18=(a18+a24);
  a36=(a36+a18);
  a17=(a17+a36);
  a21=(a21+a17);
  a23=(a23+a21);
  a8=(a8+a23);
  a34=(a34+a8);
  a11=(a11+a34);
  a31=(a31+a11);
  a26=(a26+a31);
  a4=(a4+a26);
  a12=(a12+a4);
  a2=(a2+a12);
  a2=(a2/a10);
  if (res[0]!=0) res[0][5]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_InverseKinematics_Task(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_InverseKinematics_Task_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_InverseKinematics_Task_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_InverseKinematics_Task_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_InverseKinematics_Task_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_InverseKinematics_Task_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_InverseKinematics_Task_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_InverseKinematics_Task_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_InverseKinematics_Task_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int g_InverseKinematics_Task_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_InverseKinematics_Task_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_InverseKinematics_Task_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_InverseKinematics_Task_name_out(casadi_int i){
  switch (i) {
    case 0: return "Task";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_InverseKinematics_Task_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_InverseKinematics_Task_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_InverseKinematics_Task_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* g_InverseKinematics_TaskJacobian:(q[18])->(TaskJacobian[6x18,43nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][1] : 0;
  a3=sin(a2);
  a4=-3.6596950121783327e-03;
  a5=arg[0]? arg[0][2] : 0;
  a6=sin(a5);
  a7=(a4*a6);
  a8=(a3*a7);
  a9=cos(a2);
  a10=7.3853648205019573e-03;
  a11=3.6596950121783327e-03;
  a12=cos(a5);
  a13=(a11*a12);
  a13=(a10+a13);
  a14=4.7930742348829816e-03;
  a13=(a13+a14);
  a15=(a9*a13);
  a8=(a8+a15);
  a1=(a1*a8);
  a8=3.7102242931271838e-03;
  a15=sin(a0);
  a15=(a8*a15);
  a1=(a1-a15);
  if (res[0]!=0) res[0][0]=a1;
  a1=cos(a0);
  a1=(a8*a1);
  a15=sin(a0);
  a16=(a11*a6);
  a17=(a3*a16);
  a18=-7.3853648205019573e-03;
  a19=(a4*a12);
  a19=(a18+a19);
  a20=-4.7930742348829816e-03;
  a19=(a19+a20);
  a21=(a9*a19);
  a17=(a17+a21);
  a15=(a15*a17);
  a1=(a1-a15);
  if (res[0]!=0) res[0][1]=a1;
  a1=cos(a2);
  a12=(a4*a12);
  a12=(a18+a12);
  a12=(a12+a20);
  a1=(a1*a12);
  a12=sin(a2);
  a6=(a4*a6);
  a12=(a12*a6);
  a1=(a1-a12);
  if (res[0]!=0) res[0][2]=a1;
  a1=cos(a2);
  a12=sin(a0);
  a7=(a12*a7);
  a7=(a1*a7);
  a6=sin(a2);
  a13=(a12*a13);
  a13=(a6*a13);
  a7=(a7-a13);
  if (res[0]!=0) res[0][3]=a7;
  a0=cos(a0);
  a16=(a0*a16);
  a1=(a1*a16);
  a19=(a0*a19);
  a6=(a6*a19);
  a1=(a1-a6);
  if (res[0]!=0) res[0][4]=a1;
  a1=cos(a5);
  a6=cos(a2);
  a6=(a4*a6);
  a6=(a1*a6);
  a5=sin(a5);
  a2=sin(a2);
  a2=(a4*a2);
  a2=(a5*a2);
  a6=(a6-a2);
  if (res[0]!=0) res[0][5]=a6;
  a6=(a12*a3);
  a6=(a4*a6);
  a6=(a1*a6);
  a12=(a12*a9);
  a12=(a11*a12);
  a12=(a5*a12);
  a6=(a6-a12);
  if (res[0]!=0) res[0][6]=a6;
  a3=(a0*a3);
  a3=(a11*a3);
  a1=(a1*a3);
  a0=(a0*a9);
  a0=(a4*a0);
  a5=(a5*a0);
  a1=(a1-a5);
  if (res[0]!=0) res[0][7]=a1;
  a1=arg[0]? arg[0][3] : 0;
  a5=cos(a1);
  a0=arg[0]? arg[0][4] : 0;
  a9=sin(a0);
  a3=arg[0]? arg[0][5] : 0;
  a6=sin(a3);
  a12=(a4*a6);
  a2=(a9*a12);
  a19=cos(a0);
  a16=cos(a3);
  a7=(a11*a16);
  a7=(a10+a7);
  a7=(a7+a14);
  a13=(a19*a7);
  a2=(a2+a13);
  a5=(a5*a2);
  a2=-3.7102242931271838e-03;
  a13=sin(a1);
  a13=(a2*a13);
  a5=(a5-a13);
  if (res[0]!=0) res[0][8]=a5;
  a5=cos(a1);
  a5=(a2*a5);
  a13=sin(a1);
  a15=(a11*a6);
  a17=(a9*a15);
  a21=(a4*a16);
  a21=(a18+a21);
  a21=(a21+a20);
  a22=(a19*a21);
  a17=(a17+a22);
  a13=(a13*a17);
  a5=(a5-a13);
  if (res[0]!=0) res[0][9]=a5;
  a5=cos(a0);
  a16=(a4*a16);
  a16=(a18+a16);
  a16=(a16+a20);
  a5=(a5*a16);
  a16=sin(a0);
  a6=(a4*a6);
  a16=(a16*a6);
  a5=(a5-a16);
  if (res[0]!=0) res[0][10]=a5;
  a5=cos(a0);
  a16=sin(a1);
  a12=(a16*a12);
  a12=(a5*a12);
  a6=sin(a0);
  a7=(a16*a7);
  a7=(a6*a7);
  a12=(a12-a7);
  if (res[0]!=0) res[0][11]=a12;
  a1=cos(a1);
  a15=(a1*a15);
  a5=(a5*a15);
  a21=(a1*a21);
  a6=(a6*a21);
  a5=(a5-a6);
  if (res[0]!=0) res[0][12]=a5;
  a5=cos(a3);
  a6=cos(a0);
  a6=(a4*a6);
  a6=(a5*a6);
  a3=sin(a3);
  a0=sin(a0);
  a0=(a4*a0);
  a0=(a3*a0);
  a6=(a6-a0);
  if (res[0]!=0) res[0][13]=a6;
  a6=(a16*a9);
  a6=(a4*a6);
  a6=(a5*a6);
  a16=(a16*a19);
  a16=(a11*a16);
  a16=(a3*a16);
  a6=(a6-a16);
  if (res[0]!=0) res[0][14]=a6;
  a9=(a1*a9);
  a9=(a11*a9);
  a5=(a5*a9);
  a1=(a1*a19);
  a1=(a4*a1);
  a3=(a3*a1);
  a5=(a5-a3);
  if (res[0]!=0) res[0][15]=a5;
  a5=arg[0]? arg[0][6] : 0;
  a3=cos(a5);
  a1=arg[0]? arg[0][7] : 0;
  a19=sin(a1);
  a9=5.0000000000000000e-01;
  a6=arg[0]? arg[0][8] : 0;
  a16=cos(a6);
  a0=(a9*a16);
  a21=2.6961000000000002e-01;
  a15=sin(a6);
  a12=(a21*a15);
  a0=(a0+a12);
  a12=(a19*a0);
  a7=cos(a1);
  a13=sin(a6);
  a17=(a9*a13);
  a22=-2.6961000000000002e-01;
  a23=cos(a6);
  a24=(a22*a23);
  a17=(a17+a24);
  a24=2.1149999999999999e-01;
  a17=(a17+a24);
  a24=(a7*a17);
  a12=(a12+a24);
  a12=(a3*a12);
  a24=5.7747599999999999e-01;
  a25=sin(a5);
  a26=(a24*a25);
  a12=(a12-a26);
  if (res[0]!=0) res[0][16]=a12;
  a12=cos(a5);
  a24=(a24*a12);
  a26=sin(a5);
  a27=-5.0000000000000000e-01;
  a28=(a27*a16);
  a29=(a22*a15);
  a28=(a28+a29);
  a29=(a19*a28);
  a30=(a27*a13);
  a31=(a21*a23);
  a30=(a30+a31);
  a31=-2.1149999999999999e-01;
  a30=(a30+a31);
  a32=(a7*a30);
  a29=(a29+a32);
  a29=(a26*a29);
  a24=(a24-a29);
  if (res[0]!=0) res[0][17]=a24;
  a24=(a4*a15);
  a29=(a19*a24);
  a32=(a11*a23);
  a32=(a10+a32);
  a32=(a32+a14);
  a33=(a7*a32);
  a29=(a29+a33);
  a3=(a3*a29);
  a25=(a8*a25);
  a3=(a3-a25);
  if (res[0]!=0) res[0][18]=a3;
  a8=(a8*a12);
  a12=(a11*a15);
  a3=(a19*a12);
  a25=(a4*a23);
  a25=(a18+a25);
  a25=(a25+a20);
  a29=(a7*a25);
  a3=(a3+a29);
  a26=(a26*a3);
  a8=(a8-a26);
  if (res[0]!=0) res[0][19]=a8;
  a8=cos(a1);
  a13=(a27*a13);
  a26=(a21*a23);
  a13=(a13+a26);
  a13=(a13+a31);
  a13=(a8*a13);
  a31=sin(a1);
  a16=(a9*a16);
  a26=(a21*a15);
  a16=(a16+a26);
  a16=(a31*a16);
  a13=(a13-a16);
  if (res[0]!=0) res[0][20]=a13;
  a13=cos(a1);
  a16=sin(a5);
  a0=(a16*a0);
  a0=(a13*a0);
  a26=sin(a1);
  a17=(a16*a17);
  a17=(a26*a17);
  a0=(a0-a17);
  if (res[0]!=0) res[0][21]=a0;
  a5=cos(a5);
  a28=(a5*a28);
  a28=(a13*a28);
  a30=(a5*a30);
  a30=(a26*a30);
  a28=(a28-a30);
  if (res[0]!=0) res[0][22]=a28;
  a23=(a4*a23);
  a23=(a18+a23);
  a23=(a23+a20);
  a8=(a8*a23);
  a15=(a4*a15);
  a31=(a31*a15);
  a8=(a8-a31);
  if (res[0]!=0) res[0][23]=a8;
  a24=(a16*a24);
  a24=(a13*a24);
  a32=(a16*a32);
  a32=(a26*a32);
  a24=(a24-a32);
  if (res[0]!=0) res[0][24]=a24;
  a12=(a5*a12);
  a13=(a13*a12);
  a25=(a5*a25);
  a26=(a26*a25);
  a13=(a13-a26);
  if (res[0]!=0) res[0][25]=a13;
  a13=cos(a6);
  a26=sin(a1);
  a25=(a27*a26);
  a25=(a13*a25);
  a12=sin(a6);
  a1=cos(a1);
  a24=(a9*a1);
  a24=(a12*a24);
  a25=(a25-a24);
  a24=sin(a6);
  a32=(a21*a26);
  a32=(a24*a32);
  a25=(a25-a32);
  a6=cos(a6);
  a32=(a21*a1);
  a32=(a6*a32);
  a25=(a25+a32);
  if (res[0]!=0) res[0][26]=a25;
  a25=(a16*a7);
  a32=(a9*a25);
  a32=(a13*a32);
  a16=(a16*a19);
  a9=(a9*a16);
  a9=(a12*a9);
  a32=(a32-a9);
  a9=(a22*a25);
  a9=(a24*a9);
  a32=(a32-a9);
  a9=(a21*a16);
  a9=(a6*a9);
  a32=(a32+a9);
  if (res[0]!=0) res[0][27]=a32;
  a7=(a5*a7);
  a32=(a27*a7);
  a13=(a13*a32);
  a5=(a5*a19);
  a27=(a27*a5);
  a12=(a12*a27);
  a13=(a13-a12);
  a21=(a21*a7);
  a21=(a24*a21);
  a13=(a13-a21);
  a22=(a22*a5);
  a22=(a6*a22);
  a13=(a13+a22);
  if (res[0]!=0) res[0][28]=a13;
  a1=(a4*a1);
  a1=(a6*a1);
  a26=(a4*a26);
  a26=(a24*a26);
  a1=(a1-a26);
  if (res[0]!=0) res[0][29]=a1;
  a16=(a4*a16);
  a16=(a6*a16);
  a25=(a11*a25);
  a25=(a24*a25);
  a16=(a16-a25);
  if (res[0]!=0) res[0][30]=a16;
  a5=(a11*a5);
  a6=(a6*a5);
  a7=(a4*a7);
  a24=(a24*a7);
  a6=(a6-a24);
  if (res[0]!=0) res[0][31]=a6;
  a6=arg[0]? arg[0][9] : 0;
  a24=cos(a6);
  a7=arg[0]? arg[0][10] : 0;
  a5=sin(a7);
  a16=arg[0]? arg[0][11] : 0;
  a25=sin(a16);
  a1=(a4*a25);
  a26=(a5*a1);
  a13=cos(a7);
  a22=cos(a16);
  a21=(a11*a22);
  a10=(a10+a21);
  a10=(a10+a14);
  a14=(a13*a10);
  a26=(a26+a14);
  a24=(a24*a26);
  a26=sin(a6);
  a26=(a2*a26);
  a24=(a24-a26);
  if (res[0]!=0) res[0][32]=a24;
  a24=cos(a6);
  a2=(a2*a24);
  a24=sin(a6);
  a26=(a11*a25);
  a14=(a5*a26);
  a21=(a4*a22);
  a21=(a18+a21);
  a21=(a21+a20);
  a12=(a13*a21);
  a14=(a14+a12);
  a24=(a24*a14);
  a2=(a2-a24);
  if (res[0]!=0) res[0][33]=a2;
  a2=cos(a7);
  a22=(a4*a22);
  a18=(a18+a22);
  a18=(a18+a20);
  a2=(a2*a18);
  a18=sin(a7);
  a25=(a4*a25);
  a18=(a18*a25);
  a2=(a2-a18);
  if (res[0]!=0) res[0][34]=a2;
  a2=cos(a7);
  a18=sin(a6);
  a1=(a18*a1);
  a1=(a2*a1);
  a25=sin(a7);
  a10=(a18*a10);
  a10=(a25*a10);
  a1=(a1-a10);
  if (res[0]!=0) res[0][35]=a1;
  a6=cos(a6);
  a26=(a6*a26);
  a2=(a2*a26);
  a21=(a6*a21);
  a25=(a25*a21);
  a2=(a2-a25);
  if (res[0]!=0) res[0][36]=a2;
  a2=cos(a16);
  a25=cos(a7);
  a25=(a4*a25);
  a25=(a2*a25);
  a16=sin(a16);
  a7=sin(a7);
  a7=(a4*a7);
  a7=(a16*a7);
  a25=(a25-a7);
  if (res[0]!=0) res[0][37]=a25;
  a25=(a18*a5);
  a25=(a4*a25);
  a25=(a2*a25);
  a18=(a18*a13);
  a18=(a11*a18);
  a18=(a16*a18);
  a25=(a25-a18);
  if (res[0]!=0) res[0][38]=a25;
  a5=(a6*a5);
  a11=(a11*a5);
  a2=(a2*a11);
  a6=(a6*a13);
  a4=(a4*a6);
  a16=(a16*a4);
  a2=(a2-a16);
  if (res[0]!=0) res[0][39]=a2;
  a2=3.4946521232659106e-01;
  if (res[0]!=0) res[0][40]=a2;
  if (res[0]!=0) res[0][41]=a2;
  if (res[0]!=0) res[0][42]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_InverseKinematics_TaskJacobian(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_InverseKinematics_TaskJacobian_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_InverseKinematics_TaskJacobian_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_InverseKinematics_TaskJacobian_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_InverseKinematics_TaskJacobian_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_InverseKinematics_TaskJacobian_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_InverseKinematics_TaskJacobian_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_InverseKinematics_TaskJacobian_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_InverseKinematics_TaskJacobian_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int g_InverseKinematics_TaskJacobian_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_InverseKinematics_TaskJacobian_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_InverseKinematics_TaskJacobian_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_InverseKinematics_TaskJacobian_name_out(casadi_int i){
  switch (i) {
    case 0: return "TaskJacobian";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_InverseKinematics_TaskJacobian_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_InverseKinematics_TaskJacobian_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_InverseKinematics_TaskJacobian_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* g_InverseKinematics_TaskJacobian_derivative:(q[18],v[18])->(TaskJacobian_derivative[6x18,40nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=cos(a0);
  a2=-3.6596950121783327e-03;
  a3=arg[0]? arg[0][2] : 0;
  a4=sin(a3);
  a5=(a2*a4);
  a6=arg[0]? arg[0][1] : 0;
  a7=cos(a6);
  a8=(a5*a7);
  a9=7.3853648205019573e-03;
  a10=3.6596950121783327e-03;
  a11=cos(a3);
  a12=(a10*a11);
  a12=(a9+a12);
  a13=4.7930742348829816e-03;
  a12=(a12+a13);
  a14=sin(a6);
  a15=(a12*a14);
  a8=(a8-a15);
  a8=(a1*a8);
  a15=arg[1]? arg[1][1] : 0;
  a8=(a8*a15);
  a16=sin(a6);
  a17=(a16*a5);
  a18=cos(a6);
  a19=(a18*a12);
  a17=(a17+a19);
  a19=sin(a0);
  a17=(a17*a19);
  a19=3.7102242931271838e-03;
  a20=cos(a0);
  a20=(a19*a20);
  a17=(a17+a20);
  a20=arg[1]? arg[1][0] : 0;
  a17=(a17*a20);
  a8=(a8-a17);
  a17=cos(a3);
  a21=(a2*a17);
  a22=(a16*a21);
  a23=sin(a3);
  a24=(a10*a23);
  a25=(a18*a24);
  a22=(a22-a25);
  a1=(a1*a22);
  a22=arg[1]? arg[1][2] : 0;
  a1=(a1*a22);
  a8=(a8+a1);
  if (res[0]!=0) res[0][0]=a8;
  a8=sin(a0);
  a8=(a19*a8);
  a1=(a10*a4);
  a25=(a16*a1);
  a26=-7.3853648205019573e-03;
  a27=(a2*a11);
  a27=(a26+a27);
  a28=-4.7930742348829816e-03;
  a27=(a27+a28);
  a29=(a18*a27);
  a25=(a25+a29);
  a29=cos(a0);
  a25=(a25*a29);
  a8=(a8+a25);
  a8=(a8*a20);
  a25=sin(a0);
  a29=(a1*a7);
  a30=(a27*a14);
  a29=(a29-a30);
  a29=(a25*a29);
  a29=(a29*a15);
  a8=(a8+a29);
  a29=(a10*a17);
  a30=(a16*a29);
  a31=(a2*a23);
  a32=(a18*a31);
  a30=(a30-a32);
  a25=(a25*a30);
  a25=(a25*a22);
  a8=(a8+a25);
  a8=(-a8);
  if (res[0]!=0) res[0][1]=a8;
  a11=(a2*a11);
  a11=(a26+a11);
  a11=(a11+a28);
  a8=sin(a6);
  a11=(a11*a8);
  a4=(a2*a4);
  a8=cos(a6);
  a4=(a4*a8);
  a11=(a11+a4);
  a11=(a11*a15);
  a4=cos(a6);
  a23=(a2*a23);
  a4=(a4*a23);
  a23=sin(a6);
  a17=(a2*a17);
  a23=(a23*a17);
  a4=(a4+a23);
  a4=(a4*a22);
  a11=(a11+a4);
  a11=(-a11);
  if (res[0]!=0) res[0][2]=a11;
  a11=cos(a6);
  a4=cos(a0);
  a23=(a5*a4);
  a23=(a11*a23);
  a17=sin(a6);
  a8=(a12*a4);
  a8=(a17*a8);
  a23=(a23-a8);
  a23=(a23*a20);
  a8=sin(a0);
  a5=(a8*a5);
  a25=sin(a6);
  a5=(a5*a25);
  a12=(a8*a12);
  a30=cos(a6);
  a12=(a12*a30);
  a5=(a5+a12);
  a5=(a5*a15);
  a23=(a23-a5);
  a21=(a8*a21);
  a21=(a11*a21);
  a24=(a8*a24);
  a24=(a17*a24);
  a21=(a21+a24);
  a21=(a21*a22);
  a23=(a23+a21);
  if (res[0]!=0) res[0][3]=a23;
  a23=sin(a0);
  a21=(a27*a23);
  a21=(a17*a21);
  a24=(a1*a23);
  a24=(a11*a24);
  a21=(a21-a24);
  a21=(a21*a20);
  a0=cos(a0);
  a1=(a0*a1);
  a1=(a1*a25);
  a27=(a0*a27);
  a27=(a27*a30);
  a1=(a1+a27);
  a1=(a1*a15);
  a21=(a21-a1);
  a29=(a0*a29);
  a11=(a11*a29);
  a31=(a0*a31);
  a17=(a17*a31);
  a11=(a11+a17);
  a11=(a11*a22);
  a21=(a21+a11);
  if (res[0]!=0) res[0][4]=a21;
  a21=cos(a3);
  a11=sin(a6);
  a11=(a2*a11);
  a11=(a21*a11);
  a17=sin(a3);
  a31=cos(a6);
  a31=(a2*a31);
  a31=(a17*a31);
  a11=(a11+a31);
  a11=(a11*a15);
  a31=cos(a6);
  a31=(a2*a31);
  a29=sin(a3);
  a31=(a31*a29);
  a6=sin(a6);
  a6=(a2*a6);
  a3=cos(a3);
  a6=(a6*a3);
  a31=(a31+a6);
  a31=(a31*a22);
  a11=(a11+a31);
  a11=(-a11);
  if (res[0]!=0) res[0][5]=a11;
  a11=(a16*a4);
  a11=(a2*a11);
  a11=(a21*a11);
  a4=(a18*a4);
  a4=(a10*a4);
  a4=(a17*a4);
  a11=(a11-a4);
  a11=(a11*a20);
  a4=(a8*a7);
  a4=(a2*a4);
  a4=(a21*a4);
  a31=(a8*a14);
  a31=(a10*a31);
  a31=(a17*a31);
  a4=(a4+a31);
  a4=(a4*a15);
  a11=(a11+a4);
  a4=(a8*a16);
  a4=(a2*a4);
  a4=(a4*a29);
  a8=(a8*a18);
  a8=(a10*a8);
  a8=(a8*a3);
  a4=(a4+a8);
  a4=(a4*a22);
  a11=(a11-a4);
  if (res[0]!=0) res[0][6]=a11;
  a11=(a18*a23);
  a11=(a2*a11);
  a11=(a17*a11);
  a23=(a16*a23);
  a23=(a10*a23);
  a23=(a21*a23);
  a11=(a11-a23);
  a11=(a11*a20);
  a7=(a0*a7);
  a7=(a10*a7);
  a21=(a21*a7);
  a14=(a0*a14);
  a14=(a2*a14);
  a17=(a17*a14);
  a21=(a21+a17);
  a21=(a21*a15);
  a11=(a11+a21);
  a16=(a0*a16);
  a16=(a10*a16);
  a16=(a16*a29);
  a0=(a0*a18);
  a0=(a2*a0);
  a0=(a0*a3);
  a16=(a16+a0);
  a16=(a16*a22);
  a11=(a11-a16);
  if (res[0]!=0) res[0][7]=a11;
  a11=arg[0]? arg[0][3] : 0;
  a16=cos(a11);
  a22=arg[0]? arg[0][5] : 0;
  a0=sin(a22);
  a3=(a2*a0);
  a18=arg[0]? arg[0][4] : 0;
  a29=cos(a18);
  a21=(a3*a29);
  a15=cos(a22);
  a17=(a10*a15);
  a17=(a9+a17);
  a17=(a17+a13);
  a14=sin(a18);
  a7=(a17*a14);
  a21=(a21-a7);
  a21=(a16*a21);
  a7=arg[1]? arg[1][4] : 0;
  a21=(a21*a7);
  a20=sin(a18);
  a23=(a20*a3);
  a4=cos(a18);
  a8=(a4*a17);
  a23=(a23+a8);
  a8=sin(a11);
  a23=(a23*a8);
  a8=-3.7102242931271838e-03;
  a31=cos(a11);
  a31=(a8*a31);
  a23=(a23+a31);
  a31=arg[1]? arg[1][3] : 0;
  a23=(a23*a31);
  a21=(a21-a23);
  a23=cos(a22);
  a6=(a2*a23);
  a1=(a20*a6);
  a27=sin(a22);
  a30=(a10*a27);
  a25=(a4*a30);
  a1=(a1-a25);
  a16=(a16*a1);
  a1=arg[1]? arg[1][5] : 0;
  a16=(a16*a1);
  a21=(a21+a16);
  if (res[0]!=0) res[0][8]=a21;
  a21=sin(a11);
  a21=(a8*a21);
  a16=(a10*a0);
  a25=(a20*a16);
  a24=(a2*a15);
  a24=(a26+a24);
  a24=(a24+a28);
  a5=(a4*a24);
  a25=(a25+a5);
  a5=cos(a11);
  a25=(a25*a5);
  a21=(a21+a25);
  a21=(a21*a31);
  a25=sin(a11);
  a5=(a16*a29);
  a12=(a24*a14);
  a5=(a5-a12);
  a5=(a25*a5);
  a5=(a5*a7);
  a21=(a21+a5);
  a5=(a10*a23);
  a12=(a20*a5);
  a32=(a2*a27);
  a33=(a4*a32);
  a12=(a12-a33);
  a25=(a25*a12);
  a25=(a25*a1);
  a21=(a21+a25);
  a21=(-a21);
  if (res[0]!=0) res[0][9]=a21;
  a15=(a2*a15);
  a15=(a26+a15);
  a15=(a15+a28);
  a21=sin(a18);
  a15=(a15*a21);
  a0=(a2*a0);
  a21=cos(a18);
  a0=(a0*a21);
  a15=(a15+a0);
  a15=(a15*a7);
  a0=cos(a18);
  a27=(a2*a27);
  a0=(a0*a27);
  a27=sin(a18);
  a23=(a2*a23);
  a27=(a27*a23);
  a0=(a0+a27);
  a0=(a0*a1);
  a15=(a15+a0);
  a15=(-a15);
  if (res[0]!=0) res[0][10]=a15;
  a15=cos(a18);
  a0=cos(a11);
  a27=(a3*a0);
  a27=(a15*a27);
  a23=sin(a18);
  a21=(a17*a0);
  a21=(a23*a21);
  a27=(a27-a21);
  a27=(a27*a31);
  a21=sin(a11);
  a3=(a21*a3);
  a25=sin(a18);
  a3=(a3*a25);
  a17=(a21*a17);
  a12=cos(a18);
  a17=(a17*a12);
  a3=(a3+a17);
  a3=(a3*a7);
  a27=(a27-a3);
  a6=(a21*a6);
  a6=(a15*a6);
  a30=(a21*a30);
  a30=(a23*a30);
  a6=(a6+a30);
  a6=(a6*a1);
  a27=(a27+a6);
  if (res[0]!=0) res[0][11]=a27;
  a27=sin(a11);
  a6=(a24*a27);
  a6=(a23*a6);
  a30=(a16*a27);
  a30=(a15*a30);
  a6=(a6-a30);
  a6=(a6*a31);
  a11=cos(a11);
  a16=(a11*a16);
  a16=(a16*a25);
  a24=(a11*a24);
  a24=(a24*a12);
  a16=(a16+a24);
  a16=(a16*a7);
  a6=(a6-a16);
  a5=(a11*a5);
  a15=(a15*a5);
  a32=(a11*a32);
  a23=(a23*a32);
  a15=(a15+a23);
  a15=(a15*a1);
  a6=(a6+a15);
  if (res[0]!=0) res[0][12]=a6;
  a6=cos(a22);
  a15=sin(a18);
  a15=(a2*a15);
  a15=(a6*a15);
  a23=sin(a22);
  a32=cos(a18);
  a32=(a2*a32);
  a32=(a23*a32);
  a15=(a15+a32);
  a15=(a15*a7);
  a32=cos(a18);
  a32=(a2*a32);
  a5=sin(a22);
  a32=(a32*a5);
  a18=sin(a18);
  a18=(a2*a18);
  a22=cos(a22);
  a18=(a18*a22);
  a32=(a32+a18);
  a32=(a32*a1);
  a15=(a15+a32);
  a15=(-a15);
  if (res[0]!=0) res[0][13]=a15;
  a15=(a20*a0);
  a15=(a2*a15);
  a15=(a6*a15);
  a0=(a4*a0);
  a0=(a10*a0);
  a0=(a23*a0);
  a15=(a15-a0);
  a15=(a15*a31);
  a0=(a21*a29);
  a0=(a2*a0);
  a0=(a6*a0);
  a32=(a21*a14);
  a32=(a10*a32);
  a32=(a23*a32);
  a0=(a0+a32);
  a0=(a0*a7);
  a15=(a15+a0);
  a0=(a21*a20);
  a0=(a2*a0);
  a0=(a0*a5);
  a21=(a21*a4);
  a21=(a10*a21);
  a21=(a21*a22);
  a0=(a0+a21);
  a0=(a0*a1);
  a15=(a15-a0);
  if (res[0]!=0) res[0][14]=a15;
  a15=(a4*a27);
  a15=(a2*a15);
  a15=(a23*a15);
  a27=(a20*a27);
  a27=(a10*a27);
  a27=(a6*a27);
  a15=(a15-a27);
  a15=(a15*a31);
  a29=(a11*a29);
  a29=(a10*a29);
  a6=(a6*a29);
  a14=(a11*a14);
  a14=(a2*a14);
  a23=(a23*a14);
  a6=(a6+a23);
  a6=(a6*a7);
  a15=(a15+a6);
  a20=(a11*a20);
  a20=(a10*a20);
  a20=(a20*a5);
  a11=(a11*a4);
  a11=(a2*a11);
  a11=(a11*a22);
  a20=(a20+a11);
  a20=(a20*a1);
  a15=(a15-a20);
  if (res[0]!=0) res[0][15]=a15;
  a15=arg[0]? arg[0][6] : 0;
  a20=cos(a15);
  a1=5.0000000000000000e-01;
  a11=arg[0]? arg[0][8] : 0;
  a22=cos(a11);
  a4=(a1*a22);
  a5=2.6961000000000002e-01;
  a6=sin(a11);
  a7=(a5*a6);
  a4=(a4+a7);
  a7=arg[0]? arg[0][7] : 0;
  a23=cos(a7);
  a14=(a4*a23);
  a29=sin(a11);
  a31=(a1*a29);
  a27=-2.6961000000000002e-01;
  a0=cos(a11);
  a21=(a27*a0);
  a31=(a31+a21);
  a21=2.1149999999999999e-01;
  a31=(a31+a21);
  a21=sin(a7);
  a32=(a31*a21);
  a14=(a14-a32);
  a14=(a20*a14);
  a32=arg[1]? arg[1][7] : 0;
  a14=(a14*a32);
  a18=sin(a7);
  a16=(a18*a4);
  a24=cos(a7);
  a12=(a24*a31);
  a16=(a16+a12);
  a12=sin(a15);
  a16=(a16*a12);
  a25=5.7747599999999999e-01;
  a30=cos(a15);
  a3=(a25*a30);
  a16=(a16+a3);
  a3=arg[1]? arg[1][6] : 0;
  a16=(a16*a3);
  a14=(a14-a16);
  a16=cos(a11);
  a17=(a5*a16);
  a33=sin(a11);
  a34=(a1*a33);
  a17=(a17-a34);
  a34=(a18*a17);
  a35=cos(a11);
  a36=(a1*a35);
  a37=sin(a11);
  a38=(a27*a37);
  a36=(a36-a38);
  a38=(a24*a36);
  a34=(a34+a38);
  a34=(a20*a34);
  a38=arg[1]? arg[1][8] : 0;
  a34=(a34*a38);
  a14=(a14+a34);
  if (res[0]!=0) res[0][16]=a14;
  a14=sin(a15);
  a25=(a25*a14);
  a34=-5.0000000000000000e-01;
  a39=(a34*a22);
  a40=(a27*a6);
  a39=(a39+a40);
  a40=(a18*a39);
  a41=(a34*a29);
  a42=(a5*a0);
  a41=(a41+a42);
  a42=-2.1149999999999999e-01;
  a41=(a41+a42);
  a43=(a24*a41);
  a40=(a40+a43);
  a43=cos(a15);
  a40=(a40*a43);
  a25=(a25+a40);
  a25=(a25*a3);
  a40=sin(a15);
  a44=(a39*a23);
  a45=(a41*a21);
  a44=(a44-a45);
  a44=(a40*a44);
  a44=(a44*a32);
  a25=(a25+a44);
  a44=(a27*a16);
  a45=(a34*a33);
  a44=(a44-a45);
  a45=(a18*a44);
  a46=(a34*a35);
  a47=(a5*a37);
  a46=(a46-a47);
  a47=(a24*a46);
  a45=(a45+a47);
  a45=(a40*a45);
  a45=(a45*a38);
  a25=(a25+a45);
  a25=(-a25);
  if (res[0]!=0) res[0][17]=a25;
  a25=(a2*a6);
  a45=(a25*a23);
  a47=(a10*a0);
  a47=(a9+a47);
  a47=(a47+a13);
  a48=(a47*a21);
  a45=(a45-a48);
  a45=(a20*a45);
  a45=(a45*a32);
  a48=(a18*a25);
  a49=(a24*a47);
  a48=(a48+a49);
  a48=(a48*a12);
  a30=(a19*a30);
  a48=(a48+a30);
  a48=(a48*a3);
  a45=(a45-a48);
  a48=(a2*a16);
  a30=(a18*a48);
  a12=(a10*a37);
  a49=(a24*a12);
  a30=(a30-a49);
  a20=(a20*a30);
  a20=(a20*a38);
  a45=(a45+a20);
  if (res[0]!=0) res[0][18]=a45;
  a19=(a19*a14);
  a14=(a10*a6);
  a45=(a18*a14);
  a20=(a2*a0);
  a20=(a26+a20);
  a20=(a20+a28);
  a30=(a24*a20);
  a45=(a45+a30);
  a45=(a45*a43);
  a19=(a19+a45);
  a19=(a19*a3);
  a45=(a14*a23);
  a43=(a20*a21);
  a45=(a45-a43);
  a45=(a40*a45);
  a45=(a45*a32);
  a19=(a19+a45);
  a45=(a10*a16);
  a43=(a18*a45);
  a30=(a2*a37);
  a49=(a24*a30);
  a43=(a43-a49);
  a40=(a40*a43);
  a40=(a40*a38);
  a19=(a19+a40);
  a19=(-a19);
  if (res[0]!=0) res[0][19]=a19;
  a19=cos(a7);
  a35=(a34*a35);
  a40=(a5*a37);
  a35=(a35-a40);
  a35=(a19*a35);
  a40=sin(a7);
  a43=(a5*a16);
  a33=(a1*a33);
  a43=(a43-a33);
  a43=(a40*a43);
  a35=(a35-a43);
  a35=(a35*a38);
  a29=(a34*a29);
  a43=(a5*a0);
  a29=(a29+a43);
  a29=(a29+a42);
  a42=sin(a7);
  a29=(a29*a42);
  a22=(a1*a22);
  a43=(a5*a6);
  a22=(a22+a43);
  a43=cos(a7);
  a22=(a22*a43);
  a29=(a29+a22);
  a29=(a29*a32);
  a35=(a35-a29);
  if (res[0]!=0) res[0][20]=a35;
  a35=cos(a7);
  a29=cos(a15);
  a22=(a4*a29);
  a22=(a35*a22);
  a33=sin(a7);
  a49=(a31*a29);
  a49=(a33*a49);
  a22=(a22-a49);
  a22=(a22*a3);
  a49=sin(a15);
  a4=(a49*a4);
  a50=sin(a7);
  a4=(a4*a50);
  a31=(a49*a31);
  a51=cos(a7);
  a31=(a31*a51);
  a4=(a4+a31);
  a4=(a4*a32);
  a22=(a22-a4);
  a17=(a49*a17);
  a17=(a35*a17);
  a36=(a49*a36);
  a36=(a33*a36);
  a17=(a17-a36);
  a17=(a17*a38);
  a22=(a22+a17);
  if (res[0]!=0) res[0][21]=a22;
  a22=sin(a15);
  a17=(a41*a22);
  a17=(a33*a17);
  a36=(a39*a22);
  a36=(a35*a36);
  a17=(a17-a36);
  a17=(a17*a3);
  a15=cos(a15);
  a39=(a15*a39);
  a39=(a39*a50);
  a41=(a15*a41);
  a41=(a41*a51);
  a39=(a39+a41);
  a39=(a39*a32);
  a17=(a17-a39);
  a44=(a15*a44);
  a44=(a35*a44);
  a46=(a15*a46);
  a46=(a33*a46);
  a44=(a44-a46);
  a44=(a44*a38);
  a17=(a17+a44);
  if (res[0]!=0) res[0][22]=a17;
  a0=(a2*a0);
  a0=(a26+a0);
  a0=(a0+a28);
  a0=(a0*a42);
  a6=(a2*a6);
  a6=(a6*a43);
  a0=(a0+a6);
  a0=(a0*a32);
  a37=(a2*a37);
  a19=(a19*a37);
  a16=(a2*a16);
  a40=(a40*a16);
  a19=(a19+a40);
  a19=(a19*a38);
  a0=(a0+a19);
  a0=(-a0);
  if (res[0]!=0) res[0][23]=a0;
  a0=(a25*a29);
  a0=(a35*a0);
  a19=(a47*a29);
  a19=(a33*a19);
  a0=(a0-a19);
  a0=(a0*a3);
  a25=(a49*a25);
  a25=(a25*a50);
  a47=(a49*a47);
  a47=(a47*a51);
  a25=(a25+a47);
  a25=(a25*a32);
  a0=(a0-a25);
  a48=(a49*a48);
  a48=(a35*a48);
  a12=(a49*a12);
  a12=(a33*a12);
  a48=(a48+a12);
  a48=(a48*a38);
  a0=(a0+a48);
  if (res[0]!=0) res[0][24]=a0;
  a0=(a20*a22);
  a0=(a33*a0);
  a48=(a14*a22);
  a48=(a35*a48);
  a0=(a0-a48);
  a0=(a0*a3);
  a14=(a15*a14);
  a14=(a14*a50);
  a20=(a15*a20);
  a20=(a20*a51);
  a14=(a14+a20);
  a14=(a14*a32);
  a0=(a0-a14);
  a45=(a15*a45);
  a35=(a35*a45);
  a30=(a15*a30);
  a33=(a33*a30);
  a35=(a35+a33);
  a35=(a35*a38);
  a0=(a0+a35);
  if (res[0]!=0) res[0][25]=a0;
  a0=cos(a11);
  a35=cos(a7);
  a33=(a34*a35);
  a33=(a0*a33);
  a30=sin(a11);
  a45=sin(a7);
  a14=(a1*a45);
  a14=(a30*a14);
  a33=(a33+a14);
  a14=sin(a11);
  a20=(a5*a35);
  a20=(a14*a20);
  a33=(a33-a20);
  a20=cos(a11);
  a51=(a5*a45);
  a51=(a20*a51);
  a33=(a33-a51);
  a33=(a33*a32);
  a51=sin(a7);
  a50=(a34*a51);
  a48=sin(a11);
  a50=(a50*a48);
  a7=cos(a7);
  a12=(a1*a7);
  a25=cos(a11);
  a12=(a12*a25);
  a50=(a50+a12);
  a12=(a5*a51);
  a47=cos(a11);
  a12=(a12*a47);
  a50=(a50+a12);
  a12=(a5*a7);
  a11=sin(a11);
  a12=(a12*a11);
  a50=(a50+a12);
  a50=(a50*a38);
  a33=(a33-a50);
  if (res[0]!=0) res[0][26]=a33;
  a33=(a24*a29);
  a50=(a1*a33);
  a50=(a0*a50);
  a29=(a18*a29);
  a12=(a1*a29);
  a12=(a30*a12);
  a50=(a50-a12);
  a12=(a27*a33);
  a12=(a14*a12);
  a50=(a50-a12);
  a12=(a5*a29);
  a12=(a20*a12);
  a50=(a50+a12);
  a50=(a50*a3);
  a12=(a49*a21);
  a19=(a27*a12);
  a19=(a14*a19);
  a40=(a1*a12);
  a40=(a0*a40);
  a16=(a49*a23);
  a37=(a1*a16);
  a37=(a30*a37);
  a40=(a40+a37);
  a19=(a19-a40);
  a40=(a5*a16);
  a40=(a20*a40);
  a19=(a19+a40);
  a19=(a19*a32);
  a50=(a50+a19);
  a19=(a49*a24);
  a40=(a1*a19);
  a40=(a40*a48);
  a49=(a49*a18);
  a1=(a1*a49);
  a1=(a1*a25);
  a40=(a40+a1);
  a1=(a27*a19);
  a1=(a1*a47);
  a40=(a40+a1);
  a1=(a5*a49);
  a1=(a1*a11);
  a40=(a40+a1);
  a40=(a40*a38);
  a50=(a50-a40);
  if (res[0]!=0) res[0][27]=a50;
  a50=(a18*a22);
  a40=(a34*a50);
  a40=(a30*a40);
  a22=(a24*a22);
  a1=(a34*a22);
  a1=(a0*a1);
  a40=(a40-a1);
  a1=(a5*a22);
  a1=(a14*a1);
  a40=(a40+a1);
  a1=(a27*a50);
  a1=(a20*a1);
  a40=(a40-a1);
  a40=(a40*a3);
  a21=(a15*a21);
  a1=(a5*a21);
  a1=(a14*a1);
  a37=(a34*a21);
  a0=(a0*a37);
  a23=(a15*a23);
  a37=(a34*a23);
  a30=(a30*a37);
  a0=(a0+a30);
  a1=(a1-a0);
  a0=(a27*a23);
  a0=(a20*a0);
  a1=(a1+a0);
  a1=(a1*a32);
  a40=(a40+a1);
  a24=(a15*a24);
  a1=(a34*a24);
  a1=(a1*a48);
  a15=(a15*a18);
  a34=(a34*a15);
  a34=(a34*a25);
  a1=(a1+a34);
  a5=(a5*a24);
  a5=(a5*a47);
  a1=(a1+a5);
  a27=(a27*a15);
  a27=(a27*a11);
  a1=(a1+a27);
  a1=(a1*a38);
  a40=(a40-a1);
  if (res[0]!=0) res[0][28]=a40;
  a45=(a2*a45);
  a45=(a20*a45);
  a35=(a2*a35);
  a35=(a14*a35);
  a45=(a45+a35);
  a45=(a45*a32);
  a7=(a2*a7);
  a7=(a7*a11);
  a51=(a2*a51);
  a51=(a51*a47);
  a7=(a7+a51);
  a7=(a7*a38);
  a45=(a45+a7);
  a45=(-a45);
  if (res[0]!=0) res[0][29]=a45;
  a29=(a2*a29);
  a29=(a20*a29);
  a33=(a10*a33);
  a33=(a14*a33);
  a29=(a29-a33);
  a29=(a29*a3);
  a16=(a2*a16);
  a16=(a20*a16);
  a12=(a10*a12);
  a12=(a14*a12);
  a16=(a16+a12);
  a16=(a16*a32);
  a29=(a29+a16);
  a49=(a2*a49);
  a49=(a49*a11);
  a19=(a10*a19);
  a19=(a19*a47);
  a49=(a49+a19);
  a49=(a49*a38);
  a29=(a29-a49);
  if (res[0]!=0) res[0][30]=a29;
  a22=(a2*a22);
  a22=(a14*a22);
  a50=(a10*a50);
  a50=(a20*a50);
  a22=(a22-a50);
  a22=(a22*a3);
  a23=(a10*a23);
  a20=(a20*a23);
  a21=(a2*a21);
  a14=(a14*a21);
  a20=(a20+a14);
  a20=(a20*a32);
  a22=(a22+a20);
  a15=(a10*a15);
  a15=(a15*a11);
  a24=(a2*a24);
  a24=(a24*a47);
  a15=(a15+a24);
  a15=(a15*a38);
  a22=(a22-a15);
  if (res[0]!=0) res[0][31]=a22;
  a22=arg[0]? arg[0][9] : 0;
  a15=cos(a22);
  a38=arg[0]? arg[0][11] : 0;
  a24=sin(a38);
  a47=(a2*a24);
  a11=arg[0]? arg[0][10] : 0;
  a20=cos(a11);
  a32=(a47*a20);
  a14=cos(a38);
  a21=(a10*a14);
  a9=(a9+a21);
  a9=(a9+a13);
  a13=sin(a11);
  a21=(a9*a13);
  a32=(a32-a21);
  a32=(a15*a32);
  a21=arg[1]? arg[1][10] : 0;
  a32=(a32*a21);
  a23=sin(a11);
  a3=(a23*a47);
  a50=cos(a11);
  a29=(a50*a9);
  a3=(a3+a29);
  a29=sin(a22);
  a3=(a3*a29);
  a29=cos(a22);
  a29=(a8*a29);
  a3=(a3+a29);
  a29=arg[1]? arg[1][9] : 0;
  a3=(a3*a29);
  a32=(a32-a3);
  a3=cos(a38);
  a49=(a2*a3);
  a19=(a23*a49);
  a16=sin(a38);
  a12=(a10*a16);
  a33=(a50*a12);
  a19=(a19-a33);
  a15=(a15*a19);
  a19=arg[1]? arg[1][11] : 0;
  a15=(a15*a19);
  a32=(a32+a15);
  if (res[0]!=0) res[0][32]=a32;
  a32=sin(a22);
  a8=(a8*a32);
  a32=(a10*a24);
  a15=(a23*a32);
  a33=(a2*a14);
  a33=(a26+a33);
  a33=(a33+a28);
  a45=(a50*a33);
  a15=(a15+a45);
  a45=cos(a22);
  a15=(a15*a45);
  a8=(a8+a15);
  a8=(a8*a29);
  a15=sin(a22);
  a45=(a32*a20);
  a7=(a33*a13);
  a45=(a45-a7);
  a45=(a15*a45);
  a45=(a45*a21);
  a8=(a8+a45);
  a45=(a10*a3);
  a7=(a23*a45);
  a51=(a2*a16);
  a35=(a50*a51);
  a7=(a7-a35);
  a15=(a15*a7);
  a15=(a15*a19);
  a8=(a8+a15);
  a8=(-a8);
  if (res[0]!=0) res[0][33]=a8;
  a14=(a2*a14);
  a26=(a26+a14);
  a26=(a26+a28);
  a28=sin(a11);
  a26=(a26*a28);
  a24=(a2*a24);
  a28=cos(a11);
  a24=(a24*a28);
  a26=(a26+a24);
  a26=(a26*a21);
  a24=cos(a11);
  a16=(a2*a16);
  a24=(a24*a16);
  a16=sin(a11);
  a3=(a2*a3);
  a16=(a16*a3);
  a24=(a24+a16);
  a24=(a24*a19);
  a26=(a26+a24);
  a26=(-a26);
  if (res[0]!=0) res[0][34]=a26;
  a26=cos(a11);
  a24=cos(a22);
  a16=(a47*a24);
  a16=(a26*a16);
  a3=sin(a11);
  a28=(a9*a24);
  a28=(a3*a28);
  a16=(a16-a28);
  a16=(a16*a29);
  a28=sin(a22);
  a47=(a28*a47);
  a14=sin(a11);
  a47=(a47*a14);
  a9=(a28*a9);
  a8=cos(a11);
  a9=(a9*a8);
  a47=(a47+a9);
  a47=(a47*a21);
  a16=(a16-a47);
  a49=(a28*a49);
  a49=(a26*a49);
  a12=(a28*a12);
  a12=(a3*a12);
  a49=(a49+a12);
  a49=(a49*a19);
  a16=(a16+a49);
  if (res[0]!=0) res[0][35]=a16;
  a16=sin(a22);
  a49=(a33*a16);
  a49=(a3*a49);
  a12=(a32*a16);
  a12=(a26*a12);
  a49=(a49-a12);
  a49=(a49*a29);
  a22=cos(a22);
  a32=(a22*a32);
  a32=(a32*a14);
  a33=(a22*a33);
  a33=(a33*a8);
  a32=(a32+a33);
  a32=(a32*a21);
  a49=(a49-a32);
  a45=(a22*a45);
  a26=(a26*a45);
  a51=(a22*a51);
  a3=(a3*a51);
  a26=(a26+a3);
  a26=(a26*a19);
  a49=(a49+a26);
  if (res[0]!=0) res[0][36]=a49;
  a49=cos(a38);
  a26=sin(a11);
  a26=(a2*a26);
  a26=(a49*a26);
  a3=sin(a38);
  a51=cos(a11);
  a51=(a2*a51);
  a51=(a3*a51);
  a26=(a26+a51);
  a26=(a26*a21);
  a51=cos(a11);
  a51=(a2*a51);
  a45=sin(a38);
  a51=(a51*a45);
  a11=sin(a11);
  a11=(a2*a11);
  a38=cos(a38);
  a11=(a11*a38);
  a51=(a51+a11);
  a51=(a51*a19);
  a26=(a26+a51);
  a26=(-a26);
  if (res[0]!=0) res[0][37]=a26;
  a26=(a23*a24);
  a26=(a2*a26);
  a26=(a49*a26);
  a24=(a50*a24);
  a24=(a10*a24);
  a24=(a3*a24);
  a26=(a26-a24);
  a26=(a26*a29);
  a24=(a28*a20);
  a24=(a2*a24);
  a24=(a49*a24);
  a51=(a28*a13);
  a51=(a10*a51);
  a51=(a3*a51);
  a24=(a24+a51);
  a24=(a24*a21);
  a26=(a26+a24);
  a24=(a28*a23);
  a24=(a2*a24);
  a24=(a24*a45);
  a28=(a28*a50);
  a28=(a10*a28);
  a28=(a28*a38);
  a24=(a24+a28);
  a24=(a24*a19);
  a26=(a26-a24);
  if (res[0]!=0) res[0][38]=a26;
  a26=(a50*a16);
  a26=(a2*a26);
  a26=(a3*a26);
  a16=(a23*a16);
  a16=(a10*a16);
  a16=(a49*a16);
  a26=(a26-a16);
  a26=(a26*a29);
  a20=(a22*a20);
  a20=(a10*a20);
  a49=(a49*a20);
  a13=(a22*a13);
  a13=(a2*a13);
  a3=(a3*a13);
  a49=(a49+a3);
  a49=(a49*a21);
  a26=(a26+a49);
  a23=(a22*a23);
  a10=(a10*a23);
  a10=(a10*a45);
  a22=(a22*a50);
  a2=(a2*a22);
  a2=(a2*a38);
  a10=(a10+a2);
  a10=(a10*a19);
  a26=(a26-a10);
  if (res[0]!=0) res[0][39]=a26;
  return 0;
}

CASADI_SYMBOL_EXPORT int g_InverseKinematics_TaskJacobian_derivative(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int g_InverseKinematics_TaskJacobian_derivative_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int g_InverseKinematics_TaskJacobian_derivative_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_InverseKinematics_TaskJacobian_derivative_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int g_InverseKinematics_TaskJacobian_derivative_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void g_InverseKinematics_TaskJacobian_derivative_release(int mem) {
}

CASADI_SYMBOL_EXPORT void g_InverseKinematics_TaskJacobian_derivative_incref(void) {
}

CASADI_SYMBOL_EXPORT void g_InverseKinematics_TaskJacobian_derivative_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int g_InverseKinematics_TaskJacobian_derivative_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int g_InverseKinematics_TaskJacobian_derivative_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real g_InverseKinematics_TaskJacobian_derivative_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_InverseKinematics_TaskJacobian_derivative_name_in(casadi_int i){
  switch (i) {
    case 0: return "q";
    case 1: return "v";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* g_InverseKinematics_TaskJacobian_derivative_name_out(casadi_int i){
  switch (i) {
    case 0: return "TaskJacobian_derivative";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_InverseKinematics_TaskJacobian_derivative_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* g_InverseKinematics_TaskJacobian_derivative_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int g_InverseKinematics_TaskJacobian_derivative_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
